### ISSUE TITLE
Title duplicated in subject field

### ISSUE THREAD

**Issue by ahitchner** [KnowledgeLinks/Plains2PeaksPilot#29]
Title is consistently being duplicated in the subject field across all institutions.

**Comment by jermnelson** [comment]
After doing some investigation, I think the problem may in the Marmot load. I harvested a random 250 records from Plains2Peaks and it was only in those records from Marmot institutions that have subjects that are identical or strongly similar to the title.  Checking the Marmot JSON feed (https://titan.marmot.org/API/ArchiveAPI?method=getDPLAFeed&page=1&pageSize=10), you'll see that the title is being duplicated in the subjects field that they are providing. If we don't want this duplication, we'll need to have Marmot adjust their feed or adjust the custom bibcat Marmot ingester.

Could you check to see if there are other objects that have this title duplication from non-Marmot libraries?  Otherwise, I'll close this issue.

**Comment by ahitchner** [comment]
Hi, Jeremy - It does indeed appear to only be happening with Marmot
libraries. You can go ahead and close the case. I will chat with Leigh
about how she wants to address it with Marmot.

Thanks,
Amy

Amy Hitchner
Collaborative Programming Coordinator
Colorado State Library, Networking and Resource Sharing

Web: CSL <http://www.cde.state.co.us/cdelib> | Colorado Virtual Library
<http://www.coloradovirtuallibrary.org/>
Twitter: @COStateLibrary <https://twitter.com/COStateLibrary> | @hitchlib
<https://twitter.com/hitchlib>
Facebook: Colorado State Library
<https://www.facebook.com/coloradostatelibrary/>
